version: "3"

services:
  valve_guard_ingestion_service:
    container_name: valve_guard_ingestion_service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
